package ir.mehdiyari.ctmp

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        /**
         * Print Hello World message with
         * [printHelloWorldKSP] function that generated by KSP in :ksp-processor module
         */
        Person("Richard Matthew Stallman", 69)
            .printHelloWorldKSP()
    }
}